name = "elspa-api"
type = "service"
main = "src/index.ts"
compatibility_date = "2024-12-02"

# 개발 환경
[env.development]
vars = { ENVIRONMENT = "development" }

# 프로덕션 환경
[env.production.vars]
ENVIRONMENT = "production"
SUPABASE_URL = "https://qnqhqrpvqjhqarbufzqd.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFucWhxcnB2cWpocWFyYnVmenFkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzk5NTYyODgsImV4cCI6MjA5NTUzMjI4OH0.xK6AcI7vpWDiuQzEh__5gHFKX3X6eTFH0xrgdZzRB8I"
GOOGLE_CLIENT_ID = "104694066545-vtgespl9ho6b4gmcolgdrpuloankttgq.apps.googleusercontent.com"
GOOGLE_CLIENT_SECRET = ""
